var mongoose = require('mongoose');

var Schema = mongoose.Schema;

var payuSchema = new Schema({
    // name: { type: String, required: [true, 'name is mandatory'] },
    response_code_pol: { type: String, required: [false] },
    phone: { type: String, required: [false] },
    additional_value: { type: String, required: [false] },
    test: { type: String, required: [false] },
    transaction_date: { type: String, required: [false] },
    cc_number: { type: String, required: [false] },
    cc_holder: { type: String, required: [false] },
    error_code_bank: { type: String, required: [false] },
    billing_country: { type: String, required: [false] },
    bank_referenced_name: { type: String, required: [false] },
    description: { type: String, required: [false] },
    administrative_fee_tax: { type: String, required: [false] },
    value: { type: String, required: [false] },
    administrative_fee: { type: String, required: [false] },
    payment_method_type: { type: String, required: [false] },
    office_phone: { type: String, required: [false] },
    email_buyer: { type: String, required: [false] },
    response_message_pol: { type: String, required: [false] },
    error_message_bank: { type: String, required: [false] },
    shipping_city: { type: String, required: [false] },
    transaction_id: { type: String, required: [false] },
    sign: { type: String, required: [false] },
    verify_sign: { type: String, required: [true, 'verificacion'] },
    operation_date: { type: String, required: [false] },
    tax: { type: String, required: [false] },
    transaction_bank_id: { type: String, required: [false] },
    payment_method: { type: String, required: [false] },
    billing_address: { type: String, required: [false] },
    payment_method_name: { type: String, required: [false] },
    pseCycle: { type: String, required: [false] },
    pse_bank: { type: String, required: [false] },
    state_pol: { type: String, required: [false] },
    date: { type: String, required: [false] },
    nickname_buyer: { type: String, required: [false] },
    reference_pol: { type: String, required: [false] },
    currency: { type: String, required: [false] },
    risk: { type: String, required: [false] },
    shipping_address: { type: String, required: [false] },
    bank_id: { type: String, required: [false] },
    payment_request_state: { type: String, required: [false] },
    customer_number: { type: String, required: [false] },
    administrative_fee_base: { type: String, required: [false] },
    attempts: { type: String, required: [false] },
    merchant_id: { type: String, required: [false] },
    exchange_rate: { type: String, required: [false] },
    shipping_country: { type: String, required: [false] },
    installments_number: { type: String, required: [false] },
    franchise: { type: String, required: [false] },
    payment_method_id: { type: String, required: [false] },
    extra1: { type: String, required: [false] },
    extra2: { type: String, required: [false] },
    antifraudMerchantId: { type: String, required: [false] },
    extra3: { type: String, required: [false] },
    commision_pol_currency: { type: String, required: [false] },
    nickname_seller: { type: String, required: [false] },
    ip: { type: String, required: [false] },
    commision_pol: { type: String, required: [false] },
    airline_code: { type: String, required: [false] },
    billing_city: { type: String, required: [false] },
    pse_reference1: { type: String, required: [false] },
    cus: { type: String, required: [false] },
    reference_sale: { type: String, required: [false] },
    authorization_code: { type: String, required: [false] },
    pse_reference3: { type: String, required: [false] },
    pse_reference2: { type: String, required: [false] },
}, { collection: 'payus' });

module.exports = mongoose.model('PayU', payuSchema);